centrocomputo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include('equipos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('materiales/', include('materiales.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('tipomaterial/', include('materiales.urls_tipomaterial')),
    path('', views.LoginUsuario.as_view())
]

equipos/urls.py
from django.urls import path
from . import views

app_name = 'equipos'

urlpatterns = [
    path('lista/', views.EquipoList.as_view(), name='lista'),
    path('nuevo/', views.EquipoCrear.as_view(), name='nuevo'),
    path('editar/<int:pk>', views.EquipoEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.EquipoDelete.as_view(), name='eliminar'),
    path('detalles/<int:pk>', views.EquipoDetail.as_view(), name='detalles'),
]

equipos/models.py
from django.db import models


class Equipo(models.Model):
    tipo = models.CharField("Tipo", max_length=30, unique=False)
    marca = models.CharField("Marca", max_length=30, unique=False)
    modelo = models.CharField(
        "Modelo",
        max_length=30,
        unique=False,
        blank=True,
        null=True)

    DISPONIBLE_CHOICES = [
        ('D', 'Disponible'),
        ('ND', 'No disponible'),
    ]
    disponibilidad = models.CharField(
        "Disponibilidad",
        max_length=20,
        choices=DISPONIBLE_CHOICES,
    )
    descripcion = models.CharField(
        'Descripción',
        max_length=250,
        null=True,
        blank=True)

    def __str__(self):
        return self.tipo + " " + self.marca + " " + self.modelo

equipos/forms.py
from django import forms
from .models import Equipo


class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = '__all__'
        widgets = {
            'tipo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tipo', 'require pattern': "[a-zA-Z ]{2,254}"}),
            'marca': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Marca', 'require pattern': "^[\w'\-,.][^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$"}),
            'modelo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Modelo', 'require pattern': "^\w+$"}),
            'disponibilidad': forms.Select(attrs={'class': 'forms-control'})
        }

equipos/views.py
from .models import Equipo
from .forms import EquipoForm
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin


class EquipoList(PermissionRequiredMixin, ListView):
    permission_required = 'usuarios.cajero_permiso'
    paginate_by = 10
    model = Equipo
    context_object_name = 'equipos'
    extra_context = {'etiqueta': 'Lista', 'lista_equipos': True}


class EquipoCrear(PermissionRequiredMixin, CreateView):
    permission_required = 'auth.administrador_permiso'
    model = Equipo
    form_class = EquipoForm
    extra_context = {
        'etiqueta': 'Nuevo',
        'boton': 'Agregar',
        'nuevo_equipo': True}
    success_url = reverse_lazy('equipos:lista')


class EquipoEditar(PermissionRequiredMixin, UpdateView):
    permission_required = 'usuarios.cajero_permiso'
    model = Equipo
    form_class = EquipoForm
    extra_context = {
        'etiqueta': 'Editar',
        'boton': 'Guardar',
        'edit_equipo': True}
    success_message = "El equipo se actualizó con exito"
    success_url = reverse_lazy('equipos:lista')


class EquipoDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.administrador_permiso'
    model = Equipo
    extra_context = {'etiqueta': 'Eliminar', 'del_equipo': True}
    success_url = reverse_lazy('equipos:lista')


class EquipoDetail(PermissionRequiredMixin, DetailView):
    permission_required = 'usuarios.cajero_permiso'
    model = Equipo
    extra_context = {
        'etiqueta': 'Detalles',
        'boton': 'Regresar',
        'det_equipo': True}

equipos/templates/equipos/equipo_detail.html
{% extends 'base2.html' %}
{% load static %}


{% block titulo %}
    {{etiqueta}} de Equipo
{% endblock titulo %}
    

{% block contenido %}
{% if perms.auth.administrador_permiso or perms.usuarios.cajero_permiso %}
<h1 class="app-page-title">{{etiqueta}} de Equipo</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s">
    <table class="table  table-borderless">
        <thead class="table-info">
            <th>Tipo</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Disponibilidad</th>
            <th>Descipción</th>
        </thead>
        <tbody>
            
            <tr>
                  <td>{{equipo.tipo}}</td>
                  <td>{{equipo.marca}}</td>
                  <td>{{equipo.modelo}}</td>
                  <td>{{equipo.disponibilidad}}</td>
                  <td> {{equipo.descripcion}}</td>
            </tr>
            
        </tbody>
    </table>
    
    </div>
        
    <br>
    <a href="{% url 'equipos:lista' %}" class="btn btn-info">{{boton}}</a>

{% endif %}
 {% endblock contenido %}

equipos/templates/equipos/equipo_form.html
{% extends 'base2.html' %}
{% load static %}


{% block titulo %}
    {{etiqueta}} Equipo
{% endblock titulo %}


{% block contenido %}
{% if perms.auth.administrador_permiso or perms.usuarios.cajero_permiso %}
    <h1 class="app-page-title">{{etiqueta}} Equipo</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info ">{{boton}}</button>
    </form>
{% endif %}
{% endblock contenido %}

equipos/templates/equipos/equipo_list.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    {{etiqueta}} de Equipos
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">{{etiqueta}} de Equipos</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s" id="tabla-equipos">

    <table class="table  table-borderless">
        <thead class="table-info">
            <th>Tipo</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Disponibilidad</th>
            <th>Acciones</th>
        </thead>
        <tbody>
            {% for equipo in equipos %}
            <tr>
                  <td>{{equipo.tipo}}</td>
                  <td>{{equipo.marca}}</td>
                  <td>{{equipo.modelo}}</td>
                  <td>{{equipo.disponibilidad}}</td>
                  <td>
                    <a class="btn btn-outline-primary" href="{% url 'equipos:detalles' equipo.pk %}">Detalles</a>
                    <a class="btn btn-outline-primary" href="{% url 'equipos:editar' equipo.pk %}">Editar</a>
                    <button 
                        onclick="muestraModal('{% url 'equipos:eliminar' equipo.pk %}','{{equipo.tipo}}', 'equipo')" 
                        type="button" class="btn btn-outline-primary" 
                        data-toggle="modal" data-target="#exampleModal">
                        Eliminar 
                    </button>
                  </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modalCuerpo" >         
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <form id="formEliminar" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
        </div>
      </div>
    </div>
  </div>


  <!-- Paginator -->
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Anterior </a></li>
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.number|add:"-1"}}</a></li>
    {% endif %}

    <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.number|add:"+1"}}</a></li>
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Siguiente &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
  
{% endblock contenido %}