centrocomputo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include('equipos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('materiales/', include('materiales.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('tipomaterial/', include('materiales.urls_tipomaterial')),
    path('', views.LoginUsuario.as_view())
]

equipos/urls.py
from django.urls import path
from . import views

app_name = 'equipos'

urlpatterns = [
    path('lista/', views.EquipoList.as_view(), name='lista'),
    path('nuevo/', views.EquipoCrear.as_view(), name='nuevo'),
    path('editar/<int:pk>', views.EquipoEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.EquipoDelete.as_view(), name='eliminar'),
    path('detalles/<int:pk>', views.EquipoDetail.as_view(), name='detalles'),
]

materiales/urls.py
from django.urls import path
from . import views

app_name = 'materiales'

urlpatterns = [
    path('lista/', views.MaterialList.as_view(), name='lista'),
    path('nuevo/', views.MaterialCrear.as_view(), name='nuevo'),
    path('ver/<int:pk>', views.MaterialDetalle.as_view(), name='ver'),
    path('editar/<int:pk>', views.MaterialActualizar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.MaterialDelete.as_view(), name='eliminar'),
    path('pdf/', views.MaterialesPdf.as_view(), name='pdf'),

    #path('grafica/', views.Grafica.as_view(), name='grafica'),


]

materiales/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Material(models.Model):
    #nombre = models.CharField("Nombre", max_length=30, unique=False)
    nombre = models.ForeignKey(
        "materiales.TipoMaterial",
        verbose_name="Nombre",
        on_delete=models.CASCADE)
    precio = models.DecimalField(
        'Precio',
        max_digits=6,
        decimal_places=2,
        validators=[
            MinValueValidator(0)])
    cantidad = models.PositiveIntegerField('Cantidad', default=1)
    descripcion = models.CharField(
        'Descripción',
        max_length=50,
        null=True,
        blank=True)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

    def get_precio_total(self):
        return cantidad * precio


class TipoMaterial(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

materiales/forms.py
from django import forms
from .models import Material, TipoMaterial


class TipoMaterialForm(forms.ModelForm):
    class Meta:
        model = TipoMaterial
        fields = '__all__'


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.Select(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'fecha': forms.DateField(),

        }

materiales/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Material, TipoMaterial
from .forms import MaterialForm, TipoMaterialForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django_weasyprint import WeasyTemplateResponseMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth.decorators import login_required, permission_required


@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def lista_tipomaterial(request):
    tipomateriales = TipoMaterial.objects.all()
    context = {'tipomateriales': tipomateriales, "cat_lista": True}
    return render(request, 'lista_tipomaterial.html', context)


@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def nuevo_tipomaterial(request):
    form = TipoMaterialForm()
    if request.method == 'POST':
        form = TipoMaterialForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tipomaterial:lista')

    context = {'form': form, "tmt_nueva": True}
    return render(request, 'alta_tipomaterial.html', context)


@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def eliminar_tipomaterial(request, id):
    tipomaterial = get_object_or_404(TipoMaterial, id=id)
    tipomaterial.delete()

    return redirect('tipomaterial:lista')


@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def editar_tipomaterial(request, id):
    tipomaterial = get_object_or_404(TipoMaterial, id=id)
    form = TipoMaterialForm(instance=tipomaterial)
    if request.method == 'POST':
        form = TipoMaterialForm(request.POST, instance=tipomaterial)
        if form.is_valid():
            form.save()
            return redirect('tipomaterial:lista')
    context = {'form': form, "cat_edit": True}
    return render(request, 'editar_tipomaterial.html', context)


class MaterialList(PermissionRequiredMixin, ListView):
    permission_required = 'auth.administrador_permiso'
    paginate_by = 10
    model = Material
    context_object_name = 'materiales'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}


class MaterialDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.administrador_permiso'
    model = Material
    extra_context = {'etiqueta': 'Eliminar', 'mt_del': True}
    success_url = reverse_lazy('materiales:lista')


class MaterialCrear(PermissionRequiredMixin, CreateView):
    permission_required = 'auth.administrador_permiso'
    model = Material
    form_class = MaterialForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'mt_nuevo': True}
    success_url = reverse_lazy('materiales:lista')


class MaterialActualizar(PermissionRequiredMixin, UpdateView):
    permission_required = 'auth.administrador_permiso'
    model = Material
    form_class = MaterialForm
    extra_context = {
        'etiqueta': 'Actualizar',
        'boton': 'Guardar',
        'mt_edit': True}
    success_url = reverse_lazy('materiales:lista')


class MaterialDetalle(PermissionRequiredMixin, DetailView):
    permission_required = 'auth.administrador_permiso'
    model = Material
    extra_context = {
        'etiqueta': 'Detalles',
        'boton': 'Regresar',
        'mt_det': True}


class VistaPdf(PermissionRequiredMixin, ListView):
    permission_required = 'auth.administrador_permiso'
    model = Material
    context_object_name = 'materiales'
    template_name = 'materiales/materiales_pdf.html'


class MaterialesPdf(WeasyTemplateResponseMixin, VistaPdf):
    model = Material
    pdf_attachment = False
    pdf_filename = 'Lista_materiales.pdf'

materiales/templates/materiales/material_detail.html
{% extends 'base2.html' %}


{% block titulo %}
    Detalles de Materiales
{% endblock titulo %}
    

{% block contenido %}
{% if perms.auth.administrador_permiso %}
<h1 class="app-page-title">Detalles de Materiales</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s">
    <table class="table table-borderless">
        <thead class="table-info"> 
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Descripción</th>
            <th>Fecha de Compra</th>
        </thead>
        <tbody>
            <tr>
                <td>{{object.nombre}}</td>
                <td>{{object.precio}}</td>
                <td>{{object.cantidad}}</td>                
                
                {% if object.descripcion %}
                    <td>{{object.descripcion}}</td>
                {% endif %}
                <td>{{object.fecha}}</td>
          </tr>
        </tbody>
    </table>
    
    </div>
        
    <br>
    <a href="{% url 'materiales:lista' %}" class="btn btn-info">Regresar</a>

   {% endif %} 
 {% endblock contenido %}

materiales/templates/materiales/material_form.html
{% extends 'base2.html' %}

{% block titulo %}
    {{etiqueta}} Material
{% endblock titulo %}


{% block contenido %}
{% if perms.auth.administrador_permiso %}
    <h1 class="app-page-title">{{etiqueta}} Material</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">{{boton}}</button>
    </form>

{% endif %}
{% endblock contenido %}

materiales/templates/materiales/material_list.html
{% extends 'base2.html' %}


{% block titulo %}
    Lista de Materiales
{% endblock titulo %}


{% block contenido %}
{% if perms.auth.administrador_permiso %}
<h1 class="app-page-title">Lista de Materiales</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s" id="tabla-materiales">
  
  
 
  <table class="table  table-borderless">
      <thead class="table-info">
          <th>Nombre</th>
          <th>Precio</th>
          <th>Cantidad</th>
          
          
          <th>Acciones</th>
      </thead>
      <tbody>
          {% for material in materiales %}
          <tr>
                <td>{{material.nombre}}</td>
                <td>{{material.precio}}</td>
                <td>{{material.cantidad}}</td>
                
                
                <td>
                  <div lass="btn-group" role="group" aria-label="Basic outlined example">
                    <a class="btn btn-outline-primary" href="{% url 'materiales:ver' material.pk%}">Ver</a>
                    <a class="btn btn-outline-primary"  href="{% url 'materiales:editar' material.pk %}">Editar<a></a>
                    <button 
                        onclick="muestraModal('{% url 'materiales:eliminar' material.pk %}','{{material.nombre}}')" 
                        type="button" class="btn btn-outline-primary" 
                        data-toggle="modal" data-target="#exampleModal">
                        Eliminar 
                    </button>
                    
                  </div>
                </td>
                
                
          </tr>
          {% endfor %}
      </tbody>
  </table>
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modalCuerpo" >         
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <form id="formEliminar" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Eliminar</button>
          </form>
      </div>
    </div>
  </div>
</div>
  {% endif %}

  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Anterior </a></li>
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.number|add:"-1"}}</a></li>
    {% endif %}

    <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.number|add:"+1"}}</a></li>
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Siguiente &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock contenido %}

  <!-- Button trigger modal -->

materiales/templates/materiales/materiales_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Materiales</title>
</head>
<body>
  <h1>Lista de Materiales</h1>
  <table>
    <thead>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Descripción</th>
        <th>Fecha</th>
        
        
        
    </thead>
    <tbody>
        {% for material in materiales %}
        <tr>
            <td>{{material.nombre}}</td>
            <td>{{material.precio}}</td>
            <td>{{material.cantidad}}</td>
            <td>{{material.descripcion}}</td>
            <td>{{material.fecha}}</td> 
              
        </tr>
        {% endfor %}
    </tbody>
</table>
  
</body>
</html>