centrocomputo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include('equipos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('materiales/', include('materiales.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('tipomaterial/', include('materiales.urls_tipomaterial')),
    path('', views.LoginUsuario.as_view())
]

equipos/urls.py
from django.urls import path
from . import views

app_name = 'equipos'

urlpatterns = [
    path('lista/', views.EquipoList.as_view(), name='lista'),
    path('nuevo/', views.EquipoCrear.as_view(), name='nuevo'),
    path('editar/<int:pk>', views.EquipoEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.EquipoDelete.as_view(), name='eliminar'),
    path('detalles/<int:pk>', views.EquipoDetail.as_view(), name='detalles'),
]

operaciones/urls.py
from django.urls import path
from . import views

app_name = 'operaciones'

urlpatterns = [
    path('lista/', views.OperacionList.as_view(), name='lista'),
    path('nuevo/', views.nueva_operacion, name='nuevo'),
    path(
        'eliminar/<int:pk>',
        views.OperacionDelete.as_view(),
        name='eliminar'),
    path('ver/<int:pk>', views.OperacionDetalle.as_view(), name='ver'),
    #path('validar-matricula/', views.validar_matricula, name='validar_matricula'),
]

operaciones/models.py
from django.db import models
from django.core.validators import MinValueValidator
#from usuario.models import Usuario


class Operacion(models.Model):
    #nombre = models.CharField("Nombre", max_length=50, unique=False)
    #precio_unitario = models.DecimalField(
    #    'Precio Unitario',
    #    max_digits=4,
    #    decimal_places=2,
    #    validators=[
    #        MinValueValidator(0)])
    tipo =  models.ForeignKey("operaciones.TipoOperacion", null=True,on_delete=models.CASCADE)
    cantidad = models.IntegerField(
        'Cantidad', default=1, validators=[
            MinValueValidator(1)])

    precio_total = models.DecimalField('Precio Total',null=True,max_digits=4,decimal_places=2,validators=[MinValueValidator(0)])

    #precio_total = models.DecimalField('Precio Total',decimal_places=2,max_digits=5,min_value=0)

    fecha = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(
        "usuarios.Usuario",
        verbose_name="Usuario",
        on_delete=models.CASCADE)
        
    material = models.ForeignKey(
        "materiales.TipoMaterial",
        verbose_name="Material",
        on_delete=models.CASCADE)

        
    def get_precio_total(self):
        return cantidad * precio_unitario

    def __str__(self):
        return self.nombre


class TipoOperacion(models.Model):
    nombre_tipo = models.CharField(max_length=50, verbose_name='Tipo de Operación',null=True, blank=True)
    
    precio_unitario = models.DecimalField(
        'Precio Unitario',
        max_digits=4,
        decimal_places=2,
        validators=[
            MinValueValidator(0)])

    def get_nombre(self):
        return self.nombre_tipo

    def __str__(self):
        return self.get_nombre()

    class Meta:
        verbose_name='TipoDeOperacion'
        verbose_name_plural='TiposDeOperaciones'
        db_table='tipo_oper'
        ordering=['nombre_tipo','-precio_unitario']

operaciones/forms.py
from django import forms
from .models import Operacion


class OperacionForm(forms.ModelForm):
    class Meta:
        model = Operacion

        fields = ('tipo', 'cantidad', 'material')

        widgets = {
            #'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tipo de operacion'}),
            #'precio_unitario': forms.NumberInput(attrs={'class': 'form-control'}),
            'tipo': forms.Select(attrs={'class':'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'material': forms.Select(attrs={'class': 'form-control'}),
            # 'fecha': forms.TextInput(attrs={'class':'form-control'}),
            #'usuario': forms.TextInput(attrs={'class':'form-control'}),
        }

operaciones/views.py
from contextlib import ContextDecorator
from materiales.models import TipoMaterial
from .models import Operacion
from usuarios.models import Usuario
from .forms import OperacionForm
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.template import RequestContext
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages

class OperacionList(PermissionRequiredMixin, ListView):
    permission_required = 'usuarios.cajero_permiso'
    paginate_by = 10
    model = Operacion
    context_object_name = 'operaciones'
    extra_context = {'etiqueta': 'Lista', 'oper_list': True}

class NuevaOperacion(PermissionRequiredMixin, CreateView):
    permission_required = 'auth.administrador_permiso'
    model = Operacion
    form_class = OperacionForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar'}
    success_url = reverse_lazy('operaciones:lista')


    def form_valid(self, form):
        user = form.save(commit=False)
        return super().form_valid(form)



def nueva_operacion(request):
    form = OperacionForm()
    if request.method == 'POST':
        try:
            form = OperacionForm(request.POST, request.FILES)
            matricula = request.POST['matricula']
            if matricula != "":
                matricula = matricula
            else:
                matricula = "00000000"
            #nombre = request.POST['nombre']
            #precio_unitario = request.POST['precio_unitario']
            #cantidad = request.POST['cantidad']
            #tipo= request.POST['tipo']
            if form.is_valid():
                tipo = form.cleaned_data["tipo"]
                precio = getattr(tipo,'precio_unitario')
                cantidad= form.cleaned_data.get("cantidad")
                precio_total = precio*cantidad

                #usuario = Usuario.objects.get(matricula = matricula)
                usuario = Usuario.objects.get(id = request.user.id)
                material = TipoMaterial.objects.get(id = request.POST['material'])
                oper = Operacion.objects.create(tipo=tipo,
                                            cantidad = cantidad,
                                            usuario = usuario,
                                            material = material,
                                            precio_total=precio_total)
                result = oper.save()
                if matricula != "00000000":
                    total = int(cantidad) * int(precio)
                    if total > usuario.saldo:
                        context = {'form':form, 'status': "error", 'mensaje':"No hay saldo suficiente."}
                        return render(request, 'operaciones/operacion_form.html', context) 
                    usuario.saldo -= total
                    usuario.save()
                context = {'form':form, 'status': "ok", 'mensaje':"Operación realizada."}
                return render(request, 'operaciones/operacion_form.html', context)
        except:
            print(form)
            context = {'form':form, 'status': "error", 'mensaje':"Datos incorrectos."}
            return render(request, 'operaciones/operacion_form.html', context)
    context = {'form':form, 'status': "nuevo"}
    return render(request, 'operaciones/operacion_form.html', context)


class OperacionDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'usuarios.cajero_permiso'
    model = Operacion
    extra_context = {'etiqueta': 'Eliminar', 'op_del': True}
    success_url = reverse_lazy('operaciones:lista')


class OperacionDetalle(PermissionRequiredMixin, DetailView):
    permission_required = 'usuarios.cajero_permiso'
    model = Operacion
    extra_context = {
        'etiqueta': 'Detalles',
        'boton': 'Regresar',
        'mt_det': True
    }

operaciones/templates/operaciones/operacion_detail.html
{% extends 'base2.html' %}


{% block titulo %}
    Detalles de Operación
{% endblock titulo %}
    

{% block contenido %}
<h1 class="app-page-title">Detalles de Operación</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s">
    <table class="table table-borderless">
        <thead class="table-info"> 
            <th>Usuario</th>
            <th>Operación</th>
            <th>Precio</th>
            
            <th>Cantidad</th>
            <th>Fecha</th>
            <th>Material</th>
        </thead>
        <tbody>
            <tr>
                <td>{{object.usuario}}</td>
                <!--<td>{{object.nombre}}</td>-->
                <td>{{object.tipo}}</td>
                <!--<td>{{object.precio_unitario}}</td>-->
                <td>{{object.precio_total}}</td>
                <td>{{object.cantidad}}</td>                
                <td>{{object.fecha}}</td>
                <td>{{object.material}}</td>
          </tr>
        </tbody>
    </table>
    
    </div>
        
    <br>
    <a href="{% url 'operaciones:lista' %}" class="btn btn-info">Regresar</a>
 {% endblock contenido %}

operaciones/templates/operaciones/operacion_form.html
{% extends 'base2.html' %}
{% load static %}


{% block titulo %}
    {{etiqueta}} Operación
{% endblock titulo %}


{% block contenido %}

    {% if status != 'nuevo'%}
    <div class="alert alert-{% if status == 'ok' %}success{%else%}danger{%endif%}">
        {{mensaje}}
    </div>
    {% endif %}

    <h1 class="app-page-title">{{etiqueta}} Operación</h1>
    
    <div class="form">
        <form method="POST">
            {% csrf_token %} 
            <label for="matricula" class="form-label">Matrícula</label>
            <div class="mb-3"> 
                <input name="matricula" type="text"  value="" placeholder="Matricula de usuario" id="matricula"  size="40">
                <!--<div id="matriculaHelp" class="form-text">Dejar en blanco si no eres alumno de la universidad.</div>-->

            </div>
            <br> 
            {{form.as_p}}
            
            <div>
                <button type="submit" class="btn btn-primary btn-large" id="btn_aceptar" style="margin-bottom: 1.5em;">Aceptar</button><br>
            </div>
        </form>
    </div>
{% endblock contenido %}

operaciones/templates/operaciones/operacion_list.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
     Operaciones
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">{{etiqueta}} de Operaciones</h1>

<div class="app-card app-card-orders-lable shadow-sm mb-s" id="tabla-operaciones">
      {% if not perms.usuarios.cajero_permiso %}
      <a class="btn btn-outline-primary" href="{% url 'operaciones:nuevo' %}">Operación</a>

    {% else %}
      <table class="table  table-borderless" id="tabla-operacion">
          <thead class="table-info">
              <th>Nombre</th>
              <th>Precio</th>
              <th>Cantidad</th>
              <th>Fecha</th>
              <th>Acciones</th>
          </thead>
          <tbody>
              
            


                {% for oper in operaciones %}
                <tr>
                      <!--<td>{{oper.nombre}}</td>-->
                      <td>{{oper.tipo}}</td>
                      <!--<td>{{oper.precio_unitario}}</td>-->
                      <td>{{oper.precio_total}}</td>
                      <td>{{oper.cantidad}}</td>
                      <td>{{oper.fecha}}</td>
                      <td>
                        <div lass="btn-group" role="group" aria-label="Basic outlined example">
                          <a class="btn btn-outline-primary" href="{% url 'operaciones:ver' oper.pk%}">Ver</a>
                          
                          <button 
                            onclick="muestraModal('{% url 'operaciones:eliminar' oper.pk %}','{{oper.nombre}}', 'registro')" 
                            type="button" class="btn btn-outline-primary" 
                            data-toggle="modal" data-target="#exampleModal">
                            Eliminar 
                        </button>
                          
                        </div>
                      </td>
                      
                      
                </tr>
                {% endfor %}
              
          </tbody>
      </table>
      {% endif %}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmación</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modalCuerpo" >         
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <form id="formEliminar" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
        </div>
      </div>
    </div>
  </div>

  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Anterior </a></li>
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.number|add:"-1"}}</a></li>
    {% endif %}

    <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.number|add:"+1"}}</a></li>
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Siguiente &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
  
  
{% endblock contenido %}