centrocomputo/urls.py
from django.contrib import admin
from django.urls import path, include
from usuarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipos/', include('equipos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('materiales/', include('materiales.urls')),
    path('operaciones/', include('operaciones.urls')),
    path('tipomaterial/', include('materiales.urls_tipomaterial')),
    path('', views.LoginUsuario.as_view())
]

equipos/urls.py
from django.urls import path
from . import views

app_name = 'equipos'

urlpatterns = [
    path('lista/', views.EquipoList.as_view(), name='lista'),
    path('nuevo/', views.EquipoCrear.as_view(), name='nuevo'),
    path('editar/<int:pk>', views.EquipoEditar.as_view(), name='editar'),
    path('eliminar/<int:pk>', views.EquipoDelete.as_view(), name='eliminar'),
    path('detalles/<int:pk>', views.EquipoDetail.as_view(), name='detalles'),
]

usuarios/urls.py
from django.urls import path
from . import views


app_name = 'usuarios'



urlpatterns = [
    path('lista/', views.UsuarioList.as_view(), name='lista'),
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('eliminar/<int:pk>', views.UsuarioDelete.as_view(), name='eliminar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('signup/', views.SignupUsuario.as_view(), name='signup'),
    path('cambia_grupo/<int:id_gpo>/<int:id_usuario>', views.cambia_grupo, name='cambia_grupo'),
    path('logout/', views.logout_view, name='logout'),

]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User



class Usuario(User):
    matricula = models.CharField("Matrícula", max_length=9, unique=True) 
    saldo = models.IntegerField('Saldo',default=0)
    

usuarios/forms.py
from django import forms
from .models import Usuario


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('username', 'matricula','password', 'saldo')

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'require pattern': "^[\w'\-,.][^0-9_!¡?÷?¿/\\+=@#$%ˆ&*(){}|~<>;:[\]]{2,}$"}),
            'matricula': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'forms-control', 'placeholder': 'Contraseña'}),
            'saldo': forms.NumberInput(attrs={'class': 'form-control', 'require pattern': "^[0-9]+"}),
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            return user


class UsuarioFormLog(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('matricula', 'username', 'password')

        widgets = {
            'matricula': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Matrícula', 'require pattern': "[0-9]{8}"}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'}),
            'password': forms.PasswordInput(attrs={'class': 'forms-control', 'placeholder': 'Contraseña'}),
        }

    def save(self, commit=True):
        user = super(UsuarioFormLog, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Usuario
from .forms import UsuarioForm, UsuarioFormLog
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, permission_required


def logout_view(request):
    logout(request)
    return redirect('usuarios:login')

class LoginUsuario(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

class SignupUsuario(CreateView):
    template_name = 'signup.html'
    model = Usuario
    form_class = UsuarioFormLog
    #extra_context = {'etiqueta':'Nuevo', 'boton':'Agregar', 'nuevo_user':True}
    success_url = reverse_lazy('usuarios:login')

@login_required

def editar(request, id):
    usuario = Usuario.objects.get(id=id)
    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('usuarios:lista')
    context = {'form': form }
    return render(request, 'editar_usuario.html', context) 

@login_required
@permission_required('auth.administrador_permiso', raise_exception=True)
def obtiene_usuario_grupo(request, id):
    if request.method != 'GET':
        return JsonResponse({'error':_('peticion incorrecta')},safe=False, status=403)
    id_usuario = request.GET.get('id')
    grupos = Groups.objects.filter(user_id=id_usuario)
    json=[]
    if not grupos:
        json.append({'error': _('sin grupos asignados')})
    for group in grupos:
        json.append({'id usuario':id_usuario,
        'id_grupo':grupo})
    return JsonResponse(json, safe=False)

def cambia_grupo(request, id_gpo, id_usuario):
    grupo = Group.objects.get(id=id_gpo)
    usuario= Usuario.objects.get(id=id_usuario)

    if grupo in usuario.groups.all():
        if usuario.groups.count() <= 1:
            messages.error(request, 'El usuario debe pertenecer a un grupo minimo')
        else:
            usuario.groups.remove(grupo)
            messages.success(request, 'El usuario ya no pertenece al grupo')
    else:
        usuario.groups.add(grupo)
        messages.success(request, 'El usuario se agrego al grupo')

    return redirect('usuarios:lista')


# Create your views here.
class NuevoUsuario(PermissionRequiredMixin, CreateView):
    permission_required = 'auth.administrador_permiso'
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar'}
    success_url = reverse_lazy('usuarios:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        return super().form_valid(form)

class UsuarioList(PermissionRequiredMixin, ListView):
    permission_required = ('usuarios.cajero_permiso')
    paginate_by = 10
    model = Usuario
    context_object_name = 'usuarios'
    lista_grupos = Group.objects.all()
    extra_context={'us_lista':True,
                    'lista_grupos': lista_grupos}
    
class UsuarioActualizar(PermissionRequiredMixin, UpdateView):
    
    model = Usuario
    fields = '__all__'
    extra_context = {'etiqueta': 'Actualizar', 'boton': 'Guardar'}
    success_url = reverse_lazy('usuarios:lista')


class UsuarioDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'auth.administrador_permiso'   
    model = Usuario
    success_url = reverse_lazy('usuarios:lista')
    extra_context = {'etiqueta':'Eliminar', 'user_del':True}

class UsuarioDetalle(PermissionRequiredMixin, DetailView):
    permission_required = 'usuarios.cajero_permiso'
    model = Usuario
    extra_context = {'etiqueta':'Detalles', 'boton':'Regresar'}

usuarios/templates/usuarios/usuario_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Usuario</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Quieres eliminar el usuario "{{ object }}"?</p>
        <input type="submit" value="Sí, si quiero">
        <a href="{% url 'usuarios:lista' %}">Mejor no</a>
    </form>
</body>
</html>

usuarios/templates/usuarios/usuario_detail.html
{% extends 'base2.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle del usuario</title>
</head>
<body>
    <h1>{{object.matricula}}</h1>
    
    
    {% if object.matricula %}
        <td>
            {{object.first_name}}
            {{object.saldo}}
        </td>
    {% endif %}
        
    <a href="{% url 'usuarios:lista' %}">Regresar</a>
</body>
</html>

usuarios/templates/usuarios/usuario_form.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    {{etiqueta}} usuario
{% endblock titulo %}

{% block css %}
{% endblock css %}
    

{% block contenido %}
   
    <h1>{{etiqueta}} usuario</h1>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-success">{{boton}}</button>
    </form>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/funciones.js' %}"></script>
{% endblock js %}
    

usuarios/templates/usuarios/usuario_list.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    Lista de Usuarios
{% endblock titulo %}
    

{% block contenido %}
<h1 class="app-page-title">Lista de Usuarios</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s" id="tabla-usuarios">





    <table class="table  table-borderless">
        <thead class="table-info">
            <th>Usuario</th>
            <th>Matricula</th>
            <th>Saldo</th>
            <th>Acciones</th>  
            
            {% if perms.auth.administrador_permiso %}
            <th>Eliminar</th>
            <th>Grupos</th>
                        
            {% endif %}
            
                         
            
        </thead>
        <tbody>

          
            {% for usr in usuarios %}
            
                <tr>
                    {% if not perms.auth.alumno_permiso %}
                      <td>{{usr.username}}</td>
                      <td>{{usr.matricula}}</td>
                      <td>{{usr.saldo}}</td>
                      <td><div lass="btn-group" role="group" aria-label="Basic outlined example">
                      <a  href="{% url 'usuarios:editar' usr.id %}"  class="btn btn-info" >Editar</a> </td>
                    {% endif %}
                    {% if perms.auth.administrador_permiso %}
                      <td>{{usr.username}}</td>
                      <td>{{usr.matricula}}</td>
                      <td>{{usr.saldo}}</td>
                      <td><div lass="btn-group" role="group" aria-label="Basic outlined example">
                      <a  href="{% url 'usuarios:editar' usr.id %}"  class="btn btn-info" >Editar</a> </td>
                    <td>
                      <button onclick="muestraModal('{% url 'usuarios:eliminar' usr.id %}', '{{usr.matricula}}', 'usuario')" type="button" class="btn btn-info"  data-toggle="modal" data-target="#exampleModal">
                        Eliminar
                      </button>
                  </div>
                  </td>

                    {% endif %}
                    {% if perms.auth.administrador_permiso %}
                      <td>
                        {% for grupo in lista_grupos %}
                          {% if grupo in usr.groups.all %}
                          <a href="{% url 'usuarios:cambia_grupo' grupo.id usr.id %}" class="btn btn-outline-primary">{{grupo}}</a>
                          {% else %}
                          <a href="{% url 'usuarios:cambia_grupo' grupo.id usr.id %}"class="btn btn-outline-danger">{{grupo}}</a>
                          {% endif %}
                      {% endfor %}
                      
                      </td>
                     
                    {% endif %}
                </tr>
            {% endfor %}
                
        </tbody>
    </table>
    </div>
</body>
</html>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Advertencia</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modalCuerpo">
          ¿Desea eliminar al usuario?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          <form id="formEliminar" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-info">Si</button>
          </form>
          
          
        </div>
      </div>
    </div>
  </div


  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Anterior </a></li>
        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">{{ page_obj.number|add:"-1"}}</a></li>
    {% endif %}

    <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>

    {% if page_obj.has_next %}
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">{{ page_obj.number|add:"+1"}}</a></li>
        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Siguiente &raquo;</a></li>
    {% endif %}
  </ul>
</nav>

{% endblock contenido %}


{% block js %}
    <script src="{% static 'js/funciones.js' %}" ></script>    
{% endblock js %}